name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildtest:
    runs-on: windows-latest
    steps:
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Restore packages
        run: dotnet restore

      - name: Build Debug
        run: dotnet build -c Debug

      - name: Run Tests
        run: dotnet test --no-build --filter TestCategory!=com0com

  buildrelease:
    runs-on: windows-latest
    steps:
      - name: Install .NET 6.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Restore packages
        run: dotnet restore

      - name: Build Release
        run: dotnet build -c Release -p:ContinuousIntegrationBuild=true
